### ISSUE TITLE
Server does not respond

### ISSUE THREAD

**Issue by ddeboer** [valevo/SABIO#9]
@whelmich @valevo It looks like the Docker image still doesn’t work well.

Following the instructions in https://github.com/valevo/SABIO/tree/main/docker:

```sh
$ docker build docker/
$ docker run -p 8080:8080 38794540ba26
Starting Sabio Server
datasets loaded
datasets loaded
random, content-length & vocab engine innitialised
typicality engine initialised
pmi engine initialised
random, content-length & vocab engine innitialised
typicality engine initialised
pmi engine initialised
ready! app running
ready! app running
```

However, 

```sh
curl -v http://localhost:8080
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Connection: close
< Content-Type: text/html
< Content-Length: 141
<
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>

  </body>
</html>
```

You can also try the image at https://github.com/netwerk-digitaal-erfgoed/sabio-backend/pkgs/container/sabio-backend.

**Comment by whelmich** [comment]
The current code builds a working image for me. 

That 500 error is something Valentin may want to look into. I also got the error and think that should just be a 404 not found.

When I call an URL that should exist, like `curl -v http://localhost:8080/api/v1/datasets`, it does return a correct JSON response for my front end. So from that perspective things seem to work.

**Comment by valevo** [comment]
Hi David, hi Werner (thanks for your quick reaction),

as Werner said, you're getting an error at that route because it isn't used
by the SABIO API and therefore simply not implemented. I'm not sure why
it's a 500 instead of a 404 and I won't investigate that now because
everything that *should* work also works fine for me.
I added the Swagger API specification that Werner wrote (hope you don't
mind me sharing it) to the repository
<https://github.com/valevo/SABIO/blob/main/docker/SABIO_API_v0.1.4.yml>.
That lists all the implemented routes. You can also use python test.py
--app_running <https://github.com/valevo/SABIO/blob/main/docker/test.py>
(that I run with a little venv while the docker container is running) to
test if the necessary routes all give 200 status codes (add -v to see the
actual responses).

Thanks for looking into this and please do say if there's anything else you
need.

Best,
Valentin

**Comment by ddeboer** [comment]
Ah, that makes sense! I now have an instance running at http://sabio.netwerkdigitaalerfgoed.nl.

**Comment by valevo** [comment]
Amazing :)
Thank you so much! Do you want to announce this to the others (Gertjan,
Marieke, Enno in the other email thread), I think they'll be very happy to
hear this? I can also do that if you prefer.
I'll talk to Marieke and Gertjan about next steps; we'll want to add more
datasets and maybe make small changes to the backend code. I'll get back to
you on what the best procedures could be for that once I know more
precisely what the updates will be.

Best,
Valentin
